  - name: app-setup
    include_role: 
      name: common
      tasks_from: app-setup.yaml

  - name: python-setup
    include_role: 
      name: common
      tasks_from: python-setup.yaml

  - name: systemd-setup
    include_role:
      name: common
      tasks_from: systemd-setup.yaml 
